In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

# Generating a synthetic multiclass dataset
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=20, n_classes=4, n_informative=10, random_state=42)

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initializing and training the classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Making predictions
y_pred = clf.predict(X_test)

# Generating the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Displaying the confusion matrix
print(f"Confusion Matrix:\n{conf_matrix}")

Confusion Matrix:
[[54  6  8  9]
 [ 5 59  9  2]
 [ 8  3 62  5]
 [ 6  1  4 59]]


In [2]:


# Calculating Sensitivity and Specificity for each class
n_classes = conf_matrix.shape[0]
sensitivities = []
specificities = []

for i in range(n_classes):
    # True Positives for class i
    tp = conf_matrix[i, i]

    # False Negatives for class i
    fn = np.sum(conf_matrix[i, :]) - tp

    # False Positives for class i
    fp = np.sum(conf_matrix[:, i]) - tp

    # True Negatives for class i
    tn = np.sum(conf_matrix) - (tp + fn + fp)

    # Sensitivity for class i
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    # Specificity for class i
    specificity = tn / (tn + fp)
    specificities.append(specificity)

    print(f"Class {i}: Sensitivity = {sensitivity:.2f}, Specificity = {specificity:.2f}")

# Displaying the classification report for more detailed metrics
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


Class 0: Sensitivity = 0.70, Specificity = 0.91
Class 1: Sensitivity = 0.79, Specificity = 0.96
Class 2: Sensitivity = 0.79, Specificity = 0.91
Class 3: Sensitivity = 0.84, Specificity = 0.93

Classification Report:

              precision    recall  f1-score   support

           0       0.74      0.70      0.72        77
           1       0.86      0.79      0.82        75
           2       0.75      0.79      0.77        78
           3       0.79      0.84      0.81        70

    accuracy                           0.78       300
   macro avg       0.78      0.78      0.78       300
weighted avg       0.78      0.78      0.78       300

